programa_6_1: programa_6_1.cpp Poligono.o Coordenada.o
	g++ programa_6_1.cpp Poligono.o Coordenada.o -o programa_6_1
Poligono.o: Poligono.cpp
	g++ Poligono.cpp -c
Coordenada.o: Coordenada.cpp	
	g++ Coordenada.cpp -c