programa_5_2: programa_5_2.cpp Poligono.o Coordenada.o
	g++ programa_5_2.cpp Poligono.o Coordenada.o -o programa_5_2
Poligono.o: Poligono.cpp
	g++ Poligono.cpp -c
Coordenada.o: Coordenada.cpp	
	g++ Coordenada.cpp -c